# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'WAAccountStoreDemo' do
    pod 'Mantle'
    pod 'WAAccountStore', :path => '../'
end

target 'WAAccountStoreDemoTests' do
    pod 'WAAccountStore', :path => '../'
end

